[package]
name = "emulator-core"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
keywords = { workspace = true }


[dependencies]
enum_dispatch.workspace = true
thiserror.workspace = true
